name: Contributors

on:
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Con SVG
        uses: lowlighter/metrics@latest
        with:
          user: 16Brijesh10
          filename: con.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          base: ""
          plugin_people_types: contributors, collaborators
          plugin_people_limit: 12

