name: Metrics Test

on:
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Test Skills SVG
        uses: lowlighter/metrics@latest
        with:
          user: 16Brijesh10
          filename: skills.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_topics: yes
